#!/usr/bin/env bash

 # TODO:
 # - multiple command eval (while read ...)
 # - clear toggle-able
 # - proper option parsing instead of this lmao

 ## explicitly disable history
 #set -u history

 [ "$1" == "-h" ] && { printf "\necute [-t [-v [-v [-v [-v]]]]]\n\n"; exit 0; }

 clear

 # TRAP SIGINT - make ctrl-c powerless
 [ "$1" == "-t" ] && TRAP=1
 [ -z "$TRAP" ]   && TRAP=0

 [ "$2" == "-v" ]  && VERBOSE=1
 [ "$3" == "-v" ]  && VERBOSE=2
 [ "$4" == "-v" ]  && VERBOSE=3
 [ -z "$VERBOSE" ] && VERBOSE=0

 [ "$5" == "-v" ]     && PRINT_READ=1
 [ -z "$PRINT_READ" ] && PRINT_READ=0
 
 if [ $PRINT_READ -eq 1 ]; then
 	read
 else
	 read -s
 fi

 [ $TRAP -eq 1 ] && trap "" SIGINT

 # eval "$REPLY" # >/dev/null 2>&1
 if [ $VERBOSE -eq 3 ]; then
 	bash -c "$REPLY" # allow stdout and stderr
	RET=$?
 elif [ $VERBOSE -eq 2 ]; then
 	bash -c "$REPLY" 2>/dev/null # allow stdout
	RET=$?
 elif [ "$VERBOSE" -eq 1 ]; then
 	bash -c "$REPLY" >/dev/null # allow stderr
	RET=$?
 else
 	bash -c "$REPLY" >/dev/null 2>&1
	RET=$?
 fi

 unset REPLY
 [ $TRAP -eq 1 ] && trap - SIGINT

 exit $RET

